### ISSUE TITLE
Turn TML.Patcher.CLI Into a Real Command-Line Tool

### ISSUE THREAD

**Issue by Steviegt6** [Steviegt6/TML.Patcher#13]
As it stands, TML.Patcher.CLI just prettifies the console with filler text. It should be simple and easy to also use it as an actual command-line tool with launch parameters that work quickly and efficiently. Currently, we don't provide any options.

**Comment by TomyLobo** [comment]
That would be awesome!
Right now I'm censoring out some bad words from a mod using a custom c# tool made using Mono.Cecil.
It's a chore.
Unpacking via command line is already possible, so all that's missing is repacking and I could completely automate the process.

**Comment by Steviegt6** [comment]
> That would be awesome! Right now I'm censoring out some bad words from a mod using a custom c# tool made using Mono.Cecil. It's a chore. Unpacking via command line is already possible, so all that's missing is repacking and I could completely automate the process.

Yeah, the goal is to make it entirely headless and function in a continuous integration set-up.

**Comment by Steviegt6** [comment]
Resolved in the 1.0.0 update.
